
-- CREATE
CREATE TABLE MCQQUESTIONS(ID INT auto_increment PRIMARY KEY, QUESTION VARCHAR(500), DIFFICULTY INT);

--INSERT
INSERT INTO MCQQUESTIONS(QUESTION, DIFFICULTY) VALUES ('What is CSV?', 3);

--SELECT ALL
SELECT ID, QUESTION, DIFFICULTY from MCQQUESTIONS;

-- SELECT BY ID
SELECT ID, QUESTION, DIFFICULTY from MCQQUESTIONS
where id = 1;

-- SELECT with criteria
SELECT  ID, QUESTION, DIFFICULTY from MCQQUESTIONS
where QUESTION LIKE '%Java%' 
and DIFFICULTY  < 3

--UPDATE
UPDATE MCQQUESTIONS SET QUESTION='What is JDBC?' WHERE ID=1;

--DELETE
DELETE FROM MCQQUESTIONS WHERE ID=2;


SELECT * from MCQQUESTIONS 
where ID = '1'; SELECT *  FROM USERS;;
? = 


